name: Publish docker image to rkreutz/ohs

on:
  push:
    branches:
      - 'main'
    tags:
      - '*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate DockerHub Tag
        id: generate-tag
        shell: bash
        run: |
          RAW_REF='${{ github.ref }}'
          REF=${RAW_REF/refs\/*\/}
          if [[ $REF == 'main' ]]; then
            TAG='latest'
          else
            TAG=$REF
          fi

          echo "Will push images to rkreutz/ohs:$TAG"
          echo "TAG=$TAG" >> "$GITHUB_OUTPUT"
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            rkreutz/ohs:${{ steps.generate-tag.outputs.TAG }}
          platforms: linux/amd64,linux/arm64
